server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    root: warn
  appenders:
    Console:
      name: Console
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    File:
      name: File
      fileName: logs/myapp.log
      append: true
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  loggers:
    Root:
      level: debug
      AppenderRef:
        - ref: Console
        - ref: File

spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:ytafhbfy}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/todomagic}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    check-template-location: false

